[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[program:php-fpm]
command=php-fpm -F
directory=/var/www/html
autorestart=true
priority=10
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:laravel-default-worker]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --queue=default --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=8
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/default-worker.log
stopwaitsecs=3600

[program:laravel-notifications]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --queue=notifications --sleep=3 --tries=5 --backoff=10,30,60,120,300 --timeout=30 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=3
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/notifications-worker.log
stopwaitsecs=3600

[program:laravel-notifications-critical]
process_name=%(program_name)s_%(process_num)02d
command=php artisan queue:work --queue=notifications_critical --sleep=1 --tries=5 --backoff=1,3,5,5,10 --timeout=30 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
numprocs=5
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/notifications-critical-worker.log
stopwaitsecs=3600
